name: RestAPI CI
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch_depth: 0
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Lint project
        run: yarn lint
