---
name: CI

on:
  pull_request:
    branches: main

jobs:
  build:
    name: Static code check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          # If set to false, it will only validate new/updated code
          VALIDATE_ALL_CODEBASE: true
          JAVA_FILE_NAME: checkstyle.xml
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_INCLUDE: .*src/.*