name: RestAPI Release
on:
  push:
    branches:
      - main
      - preview
jobs:
  e2e:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04]
      fail-fast: true
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use node 18.14.0
        uses: actions/setup-node@v3
        with:
          node-version: 18.14.0
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Run e2e tests
        run: yarn test:e2e
  release:
    runs-on: ubuntu-latest
    needs: e2e
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use node 18.14.0
        uses: actions/setup-node@v3
        with:
          node-version: 18.14.0
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Create release version
        run: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build docker image
        run: ./scripts/build.sh
      - name: Publish docker image
        run: |
          ./scripts/publish.sh ${{ secrets.DOCKERHUB_USERNAME }} ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Deploy docker image
        if: github.ref == 'refs/heads/main'
        run: |
          ./scripts/deploy.sh ${{ secrets.OPENSHIFT_TOKEN }} ${{ secrets.OPENSHIFT_SERVER }}
  release-preview:
    runs-on: ubuntu-latest
    needs: e2e
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Update preview
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git fetch
          git checkout preview
          git merge main --allow-unrelated-histories --strategy-option theirs --no-edit
          git push --force-with-lease
        env:
          GITHUB_TOKEN: ${{ github.GITHUB_TOKEN }}
