name: RestAPI Release
on:
  push:
    branches:
      - main
      - preview
jobs:
  e2e:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04]
      fail-fast: true
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use node 18.14.0
        uses: actions/setup-node@v3
        with:
          node-version: 18.14.0
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Run e2e tests
        run: yarn test:e2e
  tag-version:
    runs-on: ubuntu-latest
    needs: e2e
    steps:
      - name: Use node 18.14.0
        uses: actions/setup-node@v3
        with:
          node-version: 18.14.0
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Run semantic release
        run: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build docker image
        run: ./scripts/build.sh
      - name: Publish docker image
        run: |
          ./scripts/publish.sh ${{ secrets.DOCKERHUB_USERNAME }} ${{ secrets.DOCKERHUB_TOKEN }}
