name: RestAPI Release
on:
  push:
    branches:
      - main
jobs:
  e2e:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04]
      fail-fast: true
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Run e2e tests
        run: yarn test:e2e
